apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html-nginx
  template:
    metadata:
      labels:
        app: html-nginx
    spec:
      containers:
      - name: html-nginx
        image: ghcr.io/k1s3n/infraflows/html-nginx:v1.0.0
        ports:
        - containerPort: 80 
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: html-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
