name: Build and Publish Docker Image

on:
  push:
    tags:
      - 'v*'  # Trigger only on tags like "v1.0.0", "v2.1.0", etc.
      
permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/html-nginx

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract version tag
        run: echo "VERSION_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build Docker image with no cache
        run: |
          docker build --no-cache -t $IMAGE_NAME:$VERSION_TAG .

      - name: Push Docker image to GHCR
        run: |
          docker push $IMAGE_NAME:$VERSION_TAG

