name: Build and Push Docker Image to GHCR

on:
  push:
    tags:
      - 'v*'  # Den här konfigurationen triggar pipelinen när en tagg som börjar med 'v' (t.ex. v1.0.0) pushas

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image without cache
        run: |
          # Hämta taggnamnet från GitHub Actions (kommer att vara t.ex. v1.0.0)
          IMAGE_TAG=${{ github.ref_name }}  # Exempel: v1.0.0
          IMAGE_TAG=${IMAGE_TAG//[^a-zA-Z0-9._-]/_}  # Ersätter ogiltiga tecken i Docker taggar
          docker buildx build --no-cache -t ghcr.io/${{ github.repository }}/infraflow:${IMAGE_TAG} .

      - name: Push Docker image to GHCR
        run: |
          IMAGE_TAG=${{ github.ref_name }}
          IMAGE_TAG=${IMAGE_TAG//[^a-zA-Z0-9._-]/_}  # Ersätter ogiltiga tecken
          docker buildx build --no-cache -t ghcr.io/${{ github.repository }}/infraflow:${IMAGE_TAG} --push .
